const canvas = document.getElementById('world');
const ctx = canvas.getContext('2d');
const stats = document.getElementById('stats');
const seedbox = document.getElementById('seedbox');
const artifact = document.getElementById('artifact');
const providerEl = document.getElementById('provider');
const endpointEl = document.getElementById('endpoint');
const modelEl = document.getElementById('model');
const apikeyEl = document.getElementById('apikey');
let W=0,H=0,running=true,turn=0;
function resize(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
addEventListener('resize',resize);resize();
const rnd=(a=1,b=0)=>Math.random()*(a-b)+b;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function data(t){const modes=['pattern','noise','wave','text','hybrid'];const m=modes[Math.floor(Math.random()*modes.length)];let n=Math.floor(rnd(900,180));let a=[];if(m==='pattern'){let motif=['0101','ABRACADABRA','leaf-root-branch-',String.fromCharCode(t%251).repeat(8)][Math.floor(rnd(4))];while(a.join('').length<n)a.push(motif);return a.join('').slice(0,n)}if(m==='noise'){for(let i=0;i<n;i++)a.push(String.fromCharCode(Math.floor(rnd(255))));return a.join('')}if(m==='wave'){for(let i=0;i<n;i++)a.push(String.fromCharCode(Math.floor((Math.sin((i+t)/rnd(30,4))+1)*127)));return a.join('')}if(m==='text'){let w=['root','leaf','branch','flower','worldseed','compute','memory','pattern','oracle','forest'];while(a.join(' ').length<n)a.push(w[Math.floor(rnd(w.length))]);return a.join(' ').slice(0,n)}return data(t).slice(0,n/2)+data(t+1).slice(0,n/2)}
function entropy(s){let c={},n=s.length;if(!n)return 0;for(const ch of s)c[ch]=(c[ch]||0)+1;let e=0;for(const k in c){let p=c[k]/n;e-=p*Math.log2(p)}return e}
function compressionScore(s){let runs=0;for(let i=1;i<s.length;i++)if(s[i]!==s[i-1])runs++;let unique=new Set(s).size;return clamp(1-(runs/s.length)*.55-(unique/256)*.45,0,1)}
function predictScore(s){let table={},count={},ok=0,total=0;for(let i=0;i<s.length-1;i++){let a=s.charCodeAt(i),b=s.charCodeAt(i+1);table[a]=(table[a]||0)+b;count[a]=(count[a]||0)+1}for(let i=0;i<s.length-1;i++){let a=s.charCodeAt(i),b=s.charCodeAt(i+1),p=Math.round(table[a]/count[a]);if(Math.abs(p-b)<9)ok++;total++}return total?ok/total:0}
class Tree{constructor(x,y,seed){this.x=x;this.y=y;this.name=seed?.name||'Computree';this.energy=seed?.energy??35;this.branches=seed?.branches??1;this.leaves=seed?.leaves??3;this.roots=seed?.roots??1;this.flowers=seed?.flowers||[];this.memory=seed?.memory||[];this.artifacts=seed?.artifacts||[];this.g=seed?.g||{exploration:.62,compression:.72,prediction:.52,pruning:.25,mutation:.05};this.ang=rnd(Math.PI*2);this.id=hash(JSON.stringify(this.g)+Date.now()+Math.random())}
 mutate(){for(const k of Object.keys(this.g))if(Math.random()<this.g.mutation)this.g[k]=clamp(this.g[k]+rnd(.12,-.12),.01,.99)}
 compute(){let gained=0,ev=[];for(let r=0;r<this.roots;r++){let d=data(turn+r),cs=compressionScore(d),ps=predictScore(d),e=entropy(d);let target=Math.min(3,Math.max(1,Math.floor(this.leaves/18)+1));let found=false;for(let n=0;n<this.leaves*11+20;n++){if(hash(d+n).startsWith('0'.repeat(target))){found=true;break}}let val=cs*30*this.g.compression+Math.max(0,ps-.05)*20*this.g.prediction+(found?8+target*5:0);gained+=val;this.memory.push({t:turn,b:d.length,e:+e.toFixed(2),c:+cs.toFixed(2),p:+ps.toFixed(2),v:+val.toFixed(2),h:hash(d)});ev.push(val.toFixed(1))}let cost=.16*this.leaves+.36*this.branches+.22*this.roots;this.energy+=gained-cost;while(this.energy>25&&Math.random()<this.g.exploration){this.energy-=18;this.leaves++}while(this.energy>64&&Math.random()<.42){this.energy-=46;this.branches++;if(Math.random()<.34)this.roots++}if(this.energy>125&&this.memory.length>8){let tail=this.memory.slice(-12);let flower={t:turn,kind:'compressed-knowledge',value:+(tail.reduce((a,m)=>a+m.v,0)/tail.length).toFixed(2),hash:hash(JSON.stringify(tail)),summary:`${tail.length} memories compressed`};this.flowers.push(flower);this.energy-=82}if(this.energy<-18&&this.leaves>1){let lost=Math.max(1,Math.floor(this.leaves*this.g.pruning));this.leaves-=lost;this.energy+=lost*3}return ev}
 seed(){return btoa(unescape(encodeURIComponent(JSON.stringify({kind:'computree-worldseed',name:this.name,energy:this.energy*.45,branches:Math.max(1,Math.floor(this.branches/3)),leaves:Math.max(2,Math.floor(this.leaves/3)),roots:Math.max(1,Math.floor(this.roots/2)),flowers:this.flowers.slice(-6),memory:this.memory.slice(-25),artifacts:this.artifacts.slice(-3),g:this.g,hash:this.id}))))}
 draw(){let x=this.x,y=this.y;ctx.save();ctx.translate(x,y);ctx.strokeStyle='rgba(120,220,140,.75)';ctx.lineWidth=1;for(let b=0;b<this.branches;b++){let len=20+Math.log1p(Math.max(1,this.energy+80))*9+b*.7;let a=-Math.PI/2+(b-this.branches/2)*0.16+Math.sin(turn/40+b)*.12;ctx.beginPath();ctx.moveTo(0,0);let ex=Math.cos(a)*len,ey=Math.sin(a)*len;ctx.lineTo(ex,ey);ctx.stroke();for(let l=0;l<Math.min(6,this.leaves);l++){let px=ex*(l+1)/7,py=ey*(l+1)/7;ctx.fillStyle='rgba(120,255,160,.75)';ctx.beginPath();ctx.arc(px+rnd(4,-4),py+rnd(4,-4),2.2,0,Math.PI*2);ctx.fill()}}ctx.strokeStyle='rgba(95,145,255,.35)';for(let r=0;r<this.roots;r++){ctx.beginPath();ctx.moveTo(0,0);ctx.lineTo(Math.cos(this.ang+r)*30,Math.sin(this.ang+r)*30+25);ctx.stroke()}for(let f=0;f<this.flowers.length;f++){ctx.fillStyle=this.flowers[f].kind==='ai-flower'?'rgba(210,165,255,.95)':'rgba(255,230,130,.9)';ctx.beginPath();ctx.arc(Math.sin(f)*18, -40-f*3, 3.5,0,Math.PI*2);ctx.fill()}ctx.restore()}}
let forest=[new Tree(innerWidth*.5,innerHeight*.78)];
function tick(){turn++;for(const tr of forest){tr.compute();if(tr.flowers.length&&Math.random()<.004&&forest.length<18){let child=JSON.parse(decodeURIComponent(escape(atob(tr.seed()))));let t=new Tree(clamp(tr.x+rnd(160,-160),60,innerWidth-60),clamp(tr.y+rnd(100,-60),120,innerHeight-40),child);t.mutate();forest.push(t)}}}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);let grd=ctx.createRadialGradient(innerWidth/2,innerHeight/2,20,innerWidth/2,innerHeight/2,innerWidth);grd.addColorStop(0,'#0b1b10');grd.addColorStop(1,'#020503');ctx.fillStyle=grd;ctx.fillRect(0,0,innerWidth,innerHeight);for(const tr of forest)tr.draw();let ce=forest.reduce((a,t)=>a+t.energy,0),fl=forest.reduce((a,t)=>a+t.flowers.length,0);stats.textContent=`turn: ${turn}\ntrees: ${forest.length}\nenergy: ${ce.toFixed(1)} CE\nflowers: ${fl}\nlatest: ${forest[0]?.flowers.at(-1)?.summary||'growing'}`}
function loop(){if(running)tick();draw();requestAnimationFrame(loop)}loop();
function saveAISettings(){localStorage.setItem('computree-ai',JSON.stringify({provider:providerEl.value,endpoint:endpointEl.value,model:modelEl.value,apikey:apikeyEl.value}))}
function loadAISettings(){let s={provider:'ollama',endpoint:'http://localhost:11434/api/generate',model:'llama3.1',apikey:''};try{s={...s,...JSON.parse(localStorage.getItem('computree-ai')||'{}')}}catch(e){}providerEl.value=s.provider;endpointEl.value=s.endpoint;modelEl.value=s.model;apikeyEl.value=s.apikey}
loadAISettings();[providerEl,endpointEl,modelEl,apikeyEl].forEach(el=>el.onchange=saveAISettings);
providerEl.onchange=()=>{if(providerEl.value==='ollama'){endpointEl.value='http://localhost:11434/api/generate';modelEl.value=modelEl.value||'llama3.1'}else{endpointEl.value='https://api.openai.com/v1/chat/completions';modelEl.value=modelEl.value||'gpt-4o-mini'}saveAISettings()};
document.getElementById('settings').onclick=()=>document.getElementById('settingsPanel').classList.toggle('hidden');
document.getElementById('run').onclick=()=>{running=!running;document.getElementById('run').textContent=running?'pause':'run'};
document.getElementById('step').onclick=()=>tick();
document.getElementById('seed').onclick=async()=>{seedbox.value=forest[0].seed();try{await navigator.clipboard.writeText(seedbox.value)}catch(e){}};
document.getElementById('plant').onclick=()=>{try{let s=JSON.parse(decodeURIComponent(escape(atob(seedbox.value.trim()))));let t=new Tree(rnd(innerWidth-120,60),rnd(innerHeight-160,120),s);t.mutate();forest.push(t)}catch(e){seedbox.value='bad seed'}};
async function aiFlower(){let t=forest[0];saveAISettings();let settings=JSON.parse(localStorage.getItem('computree-ai')||'{}');let recent=t.memory.slice(-10);let prompt=`You are an AI flower growing on a computational tree. Create a compact useful artifact from this tree state. Return a title, a short poem or theorem, and one practical insight. State: ${JSON.stringify({turn,energy:t.energy,branches:t.branches,leaves:t.leaves,roots:t.roots,genome:t.g,recent})}`;artifact.innerHTML='AI flower growing...';try{let text='';if(settings.provider==='ollama'){let res=await fetch(settings.endpoint||'http://localhost:11434/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:settings.model||'llama3.1',prompt,stream:false})});if(!res.ok)throw new Error(await res.text());let j=await res.json();text=j.response||JSON.stringify(j)}else{let headers={'Content-Type':'application/json'};if(settings.apikey)headers.Authorization=`Bearer ${settings.apikey}`;let res=await fetch(settings.endpoint||'https://api.openai.com/v1/chat/completions',{method:'POST',headers,body:JSON.stringify({model:settings.model||'gpt-4o-mini',messages:[{role:'user',content:prompt}],temperature:.8})});if(!res.ok)throw new Error(await res.text());let j=await res.json();text=j.choices?.[0]?.message?.content||JSON.stringify(j)}let flower={t:turn,kind:'ai-flower',value:120,hash:hash(text),summary:text.slice(0,90).replace(/\s+/g,' ')+'...'};t.flowers.push(flower);t.artifacts.push({turn,hash:flower.hash,text});t.energy+=55;artifact.innerHTML=`<b>AI Flower ${flower.hash}</b><br><pre style="white-space:pre-wrap">${escapeHtml(text)}</pre>`}catch(e){let fallback=`Local symbolic flower\n\nTitle: The Branch That Earned Its Shape\n\nPoem: Roots read noise, leaves spend fire, branches remember what compression could not hide.\n\nInsight: The tree grows fastest when it finds patterns that are both compressible and predictive.\n\nError: ${e.message}`;let flower={t:turn,kind:'ai-flower',value:40,hash:hash(fallback),summary:'fallback AI flower; configure local Ollama or API'};t.flowers.push(flower);t.artifacts.push({turn,hash:flower.hash,text:fallback});t.energy+=20;artifact.innerHTML=`<b>Fallback Flower ${flower.hash}</b><br><pre style="white-space:pre-wrap">${escapeHtml(fallback)}</pre>`}}
document.getElementById('ai').onclick=aiFlower;
