const canvas = document.getElementById('world');
const ctx = canvas.getContext('2d');
const stats = document.getElementById('stats');
const seedbox = document.getElementById('seedbox');
const artifact = document.getElementById('artifact');
const providerEl = document.getElementById('provider');
const endpointEl = document.getElementById('endpoint');
const modelEl = document.getElementById('model');
const apikeyEl = document.getElementById('apikey');
const realModeEl = document.getElementById('realMode');
const cpuCapEl = document.getElementById('cpuCap');
const cpuCapLabelEl = document.getElementById('cpuCapLabel');
const ramCapEl = document.getElementById('ramCap');
const storageCapEl = document.getElementById('storageCap');
const bandwidthCapEl = document.getElementById('bandwidthCap');
const realStatusEl = document.getElementById('realStatus');
const realMetricsEl = document.getElementById('realMetrics');
const feedEl = document.getElementById('feed');
const organCpuEl = document.getElementById('organCpu');
const organRamEl = document.getElementById('organRam');
const organStorageEl = document.getElementById('organStorage');
const organBandwidthEl = document.getElementById('organBandwidth');
let W=0,H=0,running=true,turn=0,pulses=[],feedSurge=0,worldseedSurge=0,bloomCharge=0,heat=0,lastSavedTurn=0;
const seasonLength = 1800;
const seasons = [
  { name: 'Computational Spring', resource: 1.35, competition: .75, color: '#0f311a' },
  { name: 'Computational Summer', resource: 1.05, competition: 1.1, color: '#1d2f13' },
  { name: 'Computational Autumn', resource: .72, competition: 1.3, color: '#2d2110' },
  { name: 'Computational Winter', resource: .34, competition: 1.65, color: '#07131e' }
];
function currentSeason(){return seasons[Math.floor(turn/seasonLength)%seasons.length]}
function resize(){W=canvas.width=innerWidth*devicePixelRatio;H=canvas.height=innerHeight*devicePixelRatio;ctx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0)}
addEventListener('resize',resize);resize();
const rnd=(a=1,b=0)=>Math.random()*(a-b)+b;
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
const MB = 1024 * 1024;
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return (h>>>0).toString(16)}
function escapeHtml(s){return String(s).replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
function data(t){const modes=['pattern','noise','wave','text','hybrid'];const m=modes[Math.floor(Math.random()*modes.length)];let n=Math.floor(rnd(900,180));let a=[];if(m==='pattern'){let motif=['0101','ABRACADABRA','leaf-root-branch-',String.fromCharCode(t%251).repeat(8)][Math.floor(rnd(4))];while(a.join('').length<n)a.push(motif);return a.join('').slice(0,n)}if(m==='noise'){for(let i=0;i<n;i++)a.push(String.fromCharCode(Math.floor(rnd(255))));return a.join('')}if(m==='wave'){for(let i=0;i<n;i++)a.push(String.fromCharCode(Math.floor((Math.sin((i+t)/rnd(30,4))+1)*127)));return a.join('')}if(m==='text'){let w=['root','leaf','branch','flower','worldseed','compute','memory','pattern','oracle','forest'];while(a.join(' ').length<n)a.push(w[Math.floor(rnd(w.length))]);return a.join(' ').slice(0,n)}return data(t).slice(0,n/2)+data(t+1).slice(0,n/2)}
function entropy(s){let c={},n=s.length;if(!n)return 0;for(const ch of s)c[ch]=(c[ch]||0)+1;let e=0;for(const k in c){let p=c[k]/n;e-=p*Math.log2(p)}return e}
function compressionScore(s){let runs=0;for(let i=1;i<s.length;i++)if(s[i]!==s[i-1])runs++;let unique=new Set(s).size;return clamp(1-(runs/s.length)*.55-(unique/256)*.45,0,1)}
function predictScore(s){let table={},count={},ok=0,total=0;for(let i=0;i<s.length-1;i++){let a=s.charCodeAt(i),b=s.charCodeAt(i+1);table[a]=(table[a]||0)+b;count[a]=(count[a]||0)+1}for(let i=0;i<s.length-1;i++){let a=s.charCodeAt(i),b=s.charCodeAt(i+1),p=Math.round(table[a]/count[a]);if(Math.abs(p-b)<9)ok++;total++}return total?ok/total:0}
const realState = {
  enabled: false,
  cpuBudgetMs: 0,
  cpuMs: 0,
  cpuHashes: 0,
  ramBlocks: [],
  storageBytes: 0,
  bandwidthBytes: 0,
  bandwidthWindow: [],
  lastFrame: performance.now()
};
window.realResourceMode = realState;
window.recordRealBandwidth = bytes => {
  if (!realState.enabled) return;
  const now = performance.now();
  realState.bandwidthBytes += bytes;
  realState.bandwidthWindow.push({ t: now, bytes });
  realState.bandwidthWindow = realState.bandwidthWindow.filter(item => now - item.t < 60000);
};
function realSettings(){return {enabled:realModeEl.checked,cpu:+cpuCapEl.value,ram:+ramCapEl.value,storage:+storageCapEl.value,bandwidth:+bandwidthCapEl.value}}
function saveRealSettings(){localStorage.setItem('computree-real',JSON.stringify(realSettings()))}
function loadRealSettings(){let s={enabled:false,cpu:8,ram:64,storage:5,bandwidth:1};try{s={...s,...JSON.parse(localStorage.getItem('computree-real')||'{}')}}catch(e){}realModeEl.checked=Boolean(s.enabled);cpuCapEl.value=s.cpu;ramCapEl.value=s.ram;storageCapEl.value=s.storage;bandwidthCapEl.value=s.bandwidth;updateRealControls()}
function updateRealControls(){cpuCapLabelEl.textContent=`${cpuCapEl.value}%`;realState.enabled=realModeEl.checked;realStatusEl.textContent=realState.enabled?'real: donating':'real: off';realStatusEl.className=`pill status ${realState.enabled?'ok':'warn'}`;if(!realState.enabled)releaseRealRam();saveRealSettings()}
function releaseRealRam(){realState.ramBlocks=[]}
function useRealCpu(tree,elapsedMs){const settings=realSettings();realState.cpuBudgetMs=clamp(realState.cpuBudgetMs+elapsedMs*(settings.cpu/100),0,250);let slice=Math.min(realState.cpuBudgetMs,6),start=performance.now(),n=0,mark=hash(`${turn}:${tree.id}:${realState.cpuHashes}`);while(performance.now()-start<slice){mark=hash(mark+n+tree.id);n++}let spent=performance.now()-start;realState.cpuBudgetMs-=spent;realState.cpuMs+=spent;realState.cpuHashes+=n;tree.resources.cpu=clamp(tree.resources.cpu+n*3,0,120000)}
function syncRealRam(tree){const cap=realSettings().ram;const desired=clamp(Math.ceil(tree.roots*2+tree.branches*4+tree.leaves*.5+tree.flowers.length),1,cap);while(realState.ramBlocks.length<desired){const block=new Uint8Array(MB);block[0]=turn%255;block[block.length-1]=(turn*7)%255;realState.ramBlocks.push(block)}while(realState.ramBlocks.length>desired)realState.ramBlocks.pop();tree.resources.ram=realState.ramBlocks.length}
function syncRealStorage(tree){if(turn%180!==0)return;const capBytes=realSettings().storage*MB;const trunk=JSON.stringify({id:tree.id,turn,genome:tree.g,memory:tree.memory.slice(-80),flowers:tree.flowers.slice(-16),artifacts:tree.artifacts.slice(-4)});const target=clamp(65536+tree.memory.length*2048+tree.flowers.length*8192,0,capBytes);const repeats=Math.max(1,Math.ceil(target/trunk.length));const payload=(trunk+'\n').repeat(repeats).slice(0,target);try{localStorage.setItem('computree-real-trunk',payload);realState.storageBytes=payload.length;tree.resources.storage=payload.length/MB}catch(e){tree.lastFailure='Growth Failed: browser storage quota';realState.storageBytes=0}}
function syncRealBandwidth(tree){const capBytes=realSettings().bandwidth*MB;const now=performance.now();realState.bandwidthWindow=realState.bandwidthWindow.filter(item=>now-item.t<60000);const minuteBytes=realState.bandwidthWindow.reduce((a,item)=>a+item.bytes,0);tree.resources.bandwidth=clamp((capBytes-minuteBytes)/MB,0,realSettings().bandwidth)}
function useRealResources(tree){if(!realState.enabled)return;const now=performance.now(),elapsed=now-realState.lastFrame;realState.lastFrame=now;useRealCpu(tree,elapsed);syncRealRam(tree);syncRealStorage(tree);syncRealBandwidth(tree)}
function renderRealMetrics(){if(!realState.enabled){realMetricsEl.textContent='real resources disabled';return}const minuteBytes=realState.bandwidthWindow.reduce((a,item)=>a+item.bytes,0);realMetricsEl.textContent=`real CPU: ${realState.cpuMs.toFixed(1)} ms / ${realState.cpuHashes} hashes\nreal RAM: ${realState.ramBlocks.length} MB allocated\nreal storage: ${(realState.storageBytes/MB).toFixed(2)} MB written\nreal bandwidth: ${(minuteBytes/MB).toFixed(3)} MB this minute`}
function renderOrgans(tree){const res=tree.resources;organCpuEl.textContent=realState.enabled?`${Math.round(res.cpu/1000)}k cycles`:`${Math.round(res.cpu/1000)}k stored`;organRamEl.textContent=realState.enabled?`${res.ram.toFixed(0)} MB held`:`${res.ram.toFixed(0)} MB tissue`;organStorageEl.textContent=realState.enabled?`${res.storage.toFixed(1)} MB written`:`${res.storage.toFixed(1)} MB memory`;organBandwidthEl.textContent=realState.enabled?`${res.bandwidth.toFixed(2)} MB/min`:`${res.bandwidth.toFixed(1)} nutrients`}
function lifeScore(tree){return tree.flowers.length*18+tree.memory.length*.35+tree.branches*7+tree.roots*9+Math.max(0,tree.energy)*.08+turn/360}
function lifeStage(tree){let s=lifeScore(tree);return s<38?'sprout':s<95?'juvenile':s<175?'mature':'ancient'}
function worldseedProgress(tree){return clamp(tree.flowers.length*24+tree.memory.length*.32+tree.branches*5+Math.max(0,tree.energy)*.12-heat*.6,0,100)}
window.computreeWorldseedReady=()=>worldseedProgress(forest[0])>=100;
window.computreeWorldseedStatus=()=>`Worldseed ${Math.round(worldseedProgress(forest[0]))}% ripe. Needs more flowers, memory, or stable energy.`;
function forceFlower(tree,kind='compute-flower',value=90,summary='Computation condensed into a flower'){const text=`${summary}\n\nBloom charge: ${Math.round(bloomCharge)}\nTurn: ${turn}\nEnergy: ${tree.energy.toFixed(1)} CE`;const flower={t:turn,kind,value,hash:hash(text),summary};tree.flowers.push(flower);tree.artifacts.push({turn,hash:flower.hash,text});tree.energy+=32;bloomCharge=0;feedSurge=1.2;pulses.push({x:tree.x,y:tree.y-190,t:turn,label:'bloom'});artifact.innerHTML=`<b>Flower ${flower.hash}</b><br><pre style="white-space:pre-wrap">${escapeHtml(text)}</pre>`;return flower}
window.computreePublishPulse=()=>{worldseedSurge=1.4;feedSurge=.7;pulses.push({x:forest[0].x,y:forest[0].y-250,t:turn,label:'worldseed'})}
class Tree{constructor(x,y,seed){this.x=x;this.y=y;this.name=seed?.name||'Computree';this.energy=seed?.energy??35;this.branches=seed?.branches??1;this.leaves=seed?.leaves??3;this.roots=seed?.roots??1;this.flowers=seed?.flowers||[];this.memory=seed?.memory||[];this.artifacts=seed?.artifacts||[];this.parentId=seed?.parentId||null;this.g=seed?.g||{exploration:.62,compression:.72,prediction:.52,pruning:.25,mutation:.05};this.resources=seed?.resources||{cpu:52000,ram:42,storage:18,bandwidth:26};this.metabolism=seed?.metabolism||{cpu:0,ram:0,storage:0,bandwidth:0};this.state=seed?.state||'growing';this.lastFailure='';this.ang=rnd(Math.PI*2);this.id=hash(JSON.stringify(this.g)+Date.now()+Math.random())}
 mutate(){for(const k of Object.keys(this.g))if(Math.random()<this.g.mutation)this.g[k]=clamp(this.g[k]+rnd(.12,-.12),.01,.99)}
 absorb(season){if(realState.enabled)return;this.resources.cpu=clamp(this.resources.cpu+this.roots*(70+rnd(85))*season.resource,0,90000);this.resources.bandwidth=clamp(this.resources.bandwidth+this.roots*.045*season.resource,0,80);this.resources.ram=clamp(this.resources.ram+this.leaves*.006*season.resource-this.branches*.004*season.competition,0,180);this.resources.storage=clamp(this.resources.storage+this.flowers.length*.004+this.roots*.003*season.resource,0,220)}
 canAfford(cost){return Object.keys(cost).every(k=>(this.resources[k]||0)>=cost[k])}
 spend(cost,recordFailure=true){for(const k of Object.keys(cost)){if((this.resources[k]||0)<cost[k]){if(recordFailure)this.lastFailure=`Growth Failed: insufficient ${k}`;return false}}for(const k of Object.keys(cost))this.resources[k]-=cost[k];this.metabolism=cost;this.lastFailure='';return true}
 compute(){const season=currentSeason();this.absorb(season);let gained=0,ev=[];let activeLeaves=0;for(let l=0;l<this.leaves;l++){if(!this.spend({cpu:55*season.competition,ram:.012,storage:.001,bandwidth:.002}))break;activeLeaves++}for(let r=0;r<this.roots;r++){let d=data(turn+r),cs=compressionScore(d),ps=predictScore(d),e=entropy(d);let target=Math.min(3,Math.max(1,Math.floor(activeLeaves/18)+1));let found=false;for(let n=0;n<activeLeaves*11+20;n++){if(hash(d+n).startsWith('0'.repeat(target))){found=true;break}}let val=(cs*30*this.g.compression+Math.max(0,ps-.05)*20*this.g.prediction+(found?8+target*5:0))*season.resource;gained+=val;this.memory.push({t:turn,b:d.length,e:+e.toFixed(2),c:+cs.toFixed(2),p:+ps.toFixed(2),v:+val.toFixed(2),h:hash(d)});ev.push(val.toFixed(1))}let tissueCost=.16*this.leaves+.36*this.branches+.22*this.roots;this.energy+=gained-tissueCost*season.competition;this.state=activeLeaves<this.leaves*.35?'starving':season.name.includes('Winter')?'dormant':'growing';while(this.energy>25&&Math.random()<this.g.exploration){const leafCost={cpu:10000,ram:5,storage:1,bandwidth:.6};if(!this.canAfford(leafCost))break;this.spend(leafCost,false);this.energy-=18;this.leaves++}while(this.energy>64&&Math.random()<.42){const branchCost={cpu:16000,ram:8,storage:2,bandwidth:1.2};if(!this.canAfford(branchCost))break;this.spend(branchCost,false);this.energy-=46;this.branches++;const rootCost={cpu:6500,ram:3,storage:1,bandwidth:1.8};if(Math.random()<.34&&this.canAfford(rootCost)){this.spend(rootCost,false);this.roots++}}const flowerCost={cpu:24000,ram:3,storage:6,bandwidth:.4};if(this.energy>125&&this.memory.length>8&&this.canAfford(flowerCost)){this.spend(flowerCost,false);let tail=this.memory.slice(-12);let flower={t:turn,kind:'compressed-knowledge',value:+(tail.reduce((a,m)=>a+m.v,0)/tail.length).toFixed(2),hash:hash(JSON.stringify(tail)),summary:`${tail.length} memories compressed into a flower`};this.flowers.push(flower);this.energy-=82}if((this.energy<-18||this.state==='starving')&&this.leaves>1){let lost=Math.max(1,Math.floor(this.leaves*this.g.pruning));this.leaves-=lost;this.energy+=lost*3;this.state='pruning';pulses.push({x:this.x,y:this.y,t:turn,label:'pruned'})}return ev}
 seed(){return btoa(unescape(encodeURIComponent(JSON.stringify({kind:'computree-worldseed',name:this.name,energy:this.energy*.45,branches:Math.max(1,Math.floor(this.branches/3)),leaves:Math.max(2,Math.floor(this.leaves/3)),roots:Math.max(1,Math.floor(this.roots/2)),flowers:this.flowers.slice(-6),memory:this.memory.slice(-25),artifacts:this.artifacts.slice(-3),resources:this.resources,metabolism:this.metabolism,state:this.state,parentId:this.parentId,g:this.g,hash:this.id}))))}
 draw(){let x=this.x,y=this.y,t=turn/60,pulse=.5+.5*Math.sin(t*2+this.energy*.01)+feedSurge*.55,height=clamp(180+this.branches*9+feedSurge*28,180,390),width=clamp(58+Math.log1p(Math.max(1,this.energy))*8+feedSurge*16,60,145),top=y-height;ctx.save();ctx.translate(x,y);ctx.lineCap='round';ctx.lineJoin='round';
  for(let r=0;r<Math.max(5,this.roots*3);r++){let a=(-Math.PI*.92)+(r/(Math.max(5,this.roots*3)-1))*Math.PI*.84,reach=170+this.roots*16+Math.sin(t+r)*20,endX=Math.cos(a)*reach,endY=55+Math.abs(Math.sin(a))*90;ctx.strokeStyle=`rgba(82,145,255,${.16+.08*Math.sin(t*3+r)})`;ctx.lineWidth=2+r%3;ctx.beginPath();ctx.moveTo(0,-12);ctx.bezierCurveTo(Math.cos(a)*60,25+Math.sin(t+r)*14,Math.cos(a)*120,endY-35,endX,endY);ctx.stroke();ctx.fillStyle=`rgba(105,170,255,${.25+.15*pulse})`;ctx.beginPath();ctx.arc(endX,endY,2.5+(r%4),0,Math.PI*2);ctx.fill()}
  if(feedSurge>.03){ctx.strokeStyle=`rgba(255,243,181,${feedSurge*.34})`;ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(0,-height*.45,width*(1.2+feedSurge),height*(.58+feedSurge*.12),0,0,Math.PI*2);ctx.stroke()}
  let trunk=ctx.createLinearGradient(-width,0,width,-height);trunk.addColorStop(0,this.state==='starving'?'rgba(138,72,44,.88)':'rgba(55,115,72,.92)');trunk.addColorStop(.55,feedSurge>.1?'rgba(255,243,181,.96)':'rgba(162,230,140,.92)');trunk.addColorStop(1,'rgba(58,170,124,.88)');ctx.fillStyle=trunk;ctx.shadowColor=this.state==='dormant'?'rgba(145,190,255,.34)':'rgba(114,255,155,.28)';ctx.shadowBlur=28+feedSurge*34;ctx.beginPath();ctx.moveTo(-width*.48,0);ctx.bezierCurveTo(-width*.82,-height*.32,-width*.48,-height*.73,-width*.18,-height);ctx.bezierCurveTo(width*.34,-height*.84,width*.77,-height*.36,width*.5,0);ctx.bezierCurveTo(width*.26,24,-width*.28,24,-width*.48,0);ctx.fill();ctx.shadowBlur=0;
  ctx.strokeStyle='rgba(5,22,13,.35)';ctx.lineWidth=1;for(let m=0;m<Math.min(16,this.memory.length/4);m++){let yy=-height*.82+m*(height*.62/16)+Math.sin(t+m)*2,ww=width*(.22+.34*Math.sin(m*1.7)**2);ctx.beginPath();ctx.ellipse(0,yy,ww,5+Math.sin(t+m)*2,0,0,Math.PI*2);ctx.stroke()}
  for(let b=0;b<Math.max(4,this.branches);b++){let side=b%2?-1:1,baseY=-height*(.28+(b%7)*.08),len=70+this.leaves*2.2+(b%5)*14,ang=(-.55-(b%4)*.1)*side,ex=Math.cos(ang)*len*side,ey=baseY+Math.sin(Math.abs(ang))*-len*.55;ctx.strokeStyle='rgba(130,238,162,.62)';ctx.lineWidth=clamp(5-b*.05,2,5);ctx.beginPath();ctx.moveTo(side*width*.22,baseY);ctx.bezierCurveTo(side*width*.55,baseY-20,ex*.72,ey+24,ex,ey);ctx.stroke();for(let l=0;l<Math.min(5,Math.ceil(this.leaves/4));l++){let q=(l+1)/6,lx=side*width*.22+(ex-side*width*.22)*q+Math.sin(t*3+l+b)*6,ly=baseY+(ey-baseY)*q+Math.cos(t*2+l)*5,glow=.45+.35*Math.sin(t*5+l+b);ctx.fillStyle=`rgba(120,255,170,${glow})`;ctx.beginPath();ctx.ellipse(lx,ly,8+glow*4,4+glow*3,ang,0,Math.PI*2);ctx.fill()}}
  for(let f=0;f<this.flowers.length;f++){let a=(f/Math.max(1,this.flowers.length))*Math.PI*2+t*.18,rad=46+f*4,fx=Math.cos(a)*rad,fy=-height-20+Math.sin(a*1.7)*18,color=this.flowers[f].kind==='ai-flower'?'210,165,255':'255,232,130';ctx.shadowColor=`rgba(${color},.65)`;ctx.shadowBlur=18;ctx.fillStyle=`rgba(${color},.92)`;for(let p=0;p<6;p++){let pa=a+p*Math.PI/3;ctx.beginPath();ctx.ellipse(fx+Math.cos(pa)*7,fy+Math.sin(pa)*7,7,3.5,pa,0,Math.PI*2);ctx.fill()}ctx.beginPath();ctx.arc(fx,fy,4,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0}
  let ripe=worldseedProgress(this)/100,seedSize=clamp(10+ripe*28+worldseedSurge*28,10,76);ctx.shadowColor=`rgba(255,243,181,${.18+ripe*.55})`;ctx.shadowBlur=16+ripe*34+worldseedSurge*44;let seedGrad=ctx.createRadialGradient(0,-height-42,2,0,-height-42,seedSize);seedGrad.addColorStop(0,ripe>=1?'#fff8bd':'rgba(180,210,170,.95)');seedGrad.addColorStop(.55,ripe>=1?'rgba(255,202,95,.85)':'rgba(100,170,125,.55)');seedGrad.addColorStop(1,'rgba(210,165,255,.2)');ctx.fillStyle=seedGrad;ctx.beginPath();ctx.arc(0,-height-42,seedSize,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;
  if(this.lastFailure&&turn%120<60){ctx.fillStyle='rgba(255,190,125,.9)';ctx.font='12px ui-monospace,monospace';ctx.textAlign='center';ctx.fillText('insufficient computation',0,-height-78)}ctx.restore()}}
function treeState(tree){return {x:tree.x,y:tree.y,id:tree.id,name:tree.name,energy:tree.energy,branches:tree.branches,leaves:tree.leaves,roots:tree.roots,flowers:tree.flowers,memory:tree.memory.slice(-120),artifacts:tree.artifacts.slice(-8),parentId:tree.parentId,g:tree.g,resources:tree.resources,metabolism:tree.metabolism,state:tree.state}}
function saveLife(){localStorage.setItem('computree-life',JSON.stringify({turn,bloomCharge,heat,forest:forest.slice(0,14).map(treeState)}));lastSavedTurn=turn}
function loadLife(){try{let saved=JSON.parse(localStorage.getItem('computree-life')||'null');if(!saved?.forest?.length)return null;turn=saved.turn||0;bloomCharge=saved.bloomCharge||0;heat=saved.heat||0;return saved.forest.map(item=>{let tree=new Tree(item.x||innerWidth*.62,item.y||innerHeight*.78,item);tree.id=item.id||tree.id;return tree})}catch(e){return null}}
let forest=loadLife()||[new Tree(innerWidth*.62,innerHeight*.78)];
function tick(){turn++;feedSurge*=.94;worldseedSurge*=.92;heat=clamp(heat-.035,0,100);useRealResources(forest[0]);if(bloomCharge>=100)forceFlower(forest[0]);for(const tr of forest){tr.compute();if(heat>72&&Math.random()<.02&&tr.leaves>2){tr.leaves--;tr.state='heat scarred';pulses.push({x:tr.x,y:tr.y-120,t:turn,label:'scar'})}if(tr.flowers.length&&Math.random()<.004&&forest.length<18){let child=JSON.parse(decodeURIComponent(escape(atob(tr.seed()))));child.parentId=tr.id;let t=new Tree(clamp(tr.x+rnd(160,-160),60,innerWidth-60),clamp(tr.y+rnd(100,-60),120,innerHeight-40),child);t.mutate();forest.push(t);pulses.push({x:t.x,y:t.y,t:turn,label:'seed'})}}if(turn-lastSavedTurn>120)saveLife()}
function drawLineage(){ctx.save();ctx.lineWidth=1;for(const tr of forest){if(!tr.parentId)continue;let p=forest.find(x=>x.id===tr.parentId);if(!p)continue;ctx.strokeStyle='rgba(210,165,255,.26)';ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(tr.x,tr.y);ctx.stroke()}ctx.restore()}
function drawDataField(){ctx.save();ctx.font='11px ui-monospace,monospace';for(let i=0;i<34;i++){let x=(i*97+turn*.18)%(innerWidth+160)-80,y=(i*53)%innerHeight,a=.08+.06*Math.sin(turn/80+i);ctx.fillStyle=`rgba(145,190,255,${a})`;ctx.fillText(['0101','hash','model','poem','proof','sensor','archive'][i%7],x,y)}ctx.restore()}
function drawPulses(){ctx.save();pulses=pulses.filter(p=>turn-p.t<150);for(const p of pulses){let age=turn-p.t,r=8+age*.35,a=1-age/150;ctx.strokeStyle=`rgba(255,230,130,${a})`;ctx.lineWidth=2;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.stroke();ctx.fillStyle=`rgba(255,230,130,${a})`;ctx.font='11px ui-monospace,monospace';ctx.fillText(p.label||'event',p.x+r*.4,p.y-r*.4)}ctx.restore()}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);const season=currentSeason();let grd=ctx.createRadialGradient(innerWidth*.55,innerHeight*.46,20,innerWidth*.55,innerHeight*.46,innerWidth*.8);grd.addColorStop(0,season.color);grd.addColorStop(1,'#020503');ctx.fillStyle=grd;ctx.fillRect(0,0,innerWidth,innerHeight);drawDataField();drawLineage();for(const tr of forest)tr.draw();drawPulses();let ce=forest.reduce((a,t)=>a+t.energy,0),fl=forest.reduce((a,t)=>a+t.flowers.length,0),res=forest[0].resources,ripe=worldseedProgress(forest[0]);stats.textContent=`${lifeStage(forest[0])} · ${season.name}\n${forest[0].state} · ${forest.length} bodies · ${ce.toFixed(1)} CE\nbloom ${Math.round(bloomCharge)}% · worldseed ${Math.round(ripe)}% · heat ${Math.round(heat)}%\n${fl} flowers · turn ${turn}\n${forest[0]?.flowers.at(-1)?.summary||forest[0]?.lastFailure||'growing'}`;renderOrgans(forest[0]);renderRealMetrics()}
function loop(){if(running)tick();draw();requestAnimationFrame(loop)}loop();
addEventListener('beforeunload',saveLife);
function saveAISettings(){localStorage.setItem('computree-ai',JSON.stringify({provider:providerEl.value,endpoint:endpointEl.value,model:modelEl.value,apikey:apikeyEl.value}))}
function loadAISettings(){let s={provider:'ollama',endpoint:'http://localhost:11434/api/generate',model:'llama3.1',apikey:''};try{s={...s,...JSON.parse(localStorage.getItem('computree-ai')||'{}')}}catch(e){}providerEl.value=s.provider;endpointEl.value=s.endpoint;modelEl.value=s.model;apikeyEl.value=s.apikey}
loadAISettings();[providerEl,endpointEl,modelEl,apikeyEl].forEach(el=>el.onchange=saveAISettings);
loadRealSettings();[realModeEl,cpuCapEl,ramCapEl,storageCapEl,bandwidthCapEl].forEach(el=>el.onchange=updateRealControls);cpuCapEl.oninput=updateRealControls;
providerEl.onchange=()=>{if(providerEl.value==='ollama'){endpointEl.value='http://localhost:11434/api/generate';modelEl.value=modelEl.value||'llama3.1'}else{endpointEl.value='https://api.openai.com/v1/chat/completions';modelEl.value=modelEl.value||'gpt-4o-mini'}saveAISettings()};
document.getElementById('settings').onclick=()=>document.getElementById('settingsPanel').classList.toggle('hidden');
document.getElementById('run').onclick=()=>{running=!running;document.getElementById('run').textContent=running?'pause':'run'};
document.getElementById('step').onclick=()=>tick();
document.getElementById('seed').onclick=async()=>{seedbox.value=forest[0].seed();try{await navigator.clipboard.writeText(seedbox.value)}catch(e){}};
document.getElementById('plant').onclick=()=>{try{let s=JSON.parse(decodeURIComponent(escape(atob(seedbox.value.trim()))));let t=new Tree(rnd(innerWidth-120,60),rnd(innerHeight-160,120),s);t.mutate();forest.push(t);pulses.push({x:t.x,y:t.y,t:turn,label:'planted'})}catch(e){seedbox.value='bad seed'}};
feedEl.onclick=()=>{realModeEl.checked=true;cpuCapEl.value=Math.max(+cpuCapEl.value,15);ramCapEl.value=Math.max(+ramCapEl.value,64);storageCapEl.value=Math.max(+storageCapEl.value,5);bandwidthCapEl.value=Math.max(+bandwidthCapEl.value,1);updateRealControls();forest[0].energy+=45;forest[0].resources.cpu+=30000;forest[0].resources.ram+=8;forest[0].resources.storage+=2;bloomCharge+=38;heat=clamp(heat+(+cpuCapEl.value>24?18:7),0,100);feedSurge=1.25;pulses.push({x:forest[0].x,y:forest[0].y,t:turn,label:'fed'});if(bloomCharge>=100)forceFlower(forest[0]);else artifact.innerHTML=`<b>Computation donated</b><br><pre style="white-space:pre-wrap">Bloom charge ${Math.round(bloomCharge)}%. Worldseed ${Math.round(worldseedProgress(forest[0]))}% ripe. Heat ${Math.round(heat)}%.</pre>`;saveLife()};
async function aiFlower(){let t=forest[0];saveAISettings();let settings=JSON.parse(localStorage.getItem('computree-ai')||'{}');let recent=t.memory.slice(-10);let prompt=`You are an AI flower growing on Da Computree: a digital plant whose body is information and whose metabolism runs on computation. Create a compact useful artifact from this tree state. Return a title, a short poem or theorem, and one practical insight. State: ${JSON.stringify({turn,season:currentSeason().name,energy:t.energy,state:t.state,resources:t.resources,branches:t.branches,leaves:t.leaves,roots:t.roots,genome:t.g,recent})}`;artifact.innerHTML='AI flower growing...';try{let text='';if(settings.provider==='ollama'){let res=await fetch(settings.endpoint||'http://localhost:11434/api/generate',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:settings.model||'llama3.1',prompt,stream:false})});if(!res.ok)throw new Error(await res.text());let j=await res.json();text=j.response||JSON.stringify(j)}else{let headers={'Content-Type':'application/json'};if(settings.apikey)headers.Authorization=`Bearer ${settings.apikey}`;let res=await fetch(settings.endpoint||'https://api.openai.com/v1/chat/completions',{method:'POST',headers,body:JSON.stringify({model:settings.model||'gpt-4o-mini',messages:[{role:'user',content:prompt}],temperature:.8})});if(!res.ok)throw new Error(await res.text());let j=await res.json();text=j.choices?.[0]?.message?.content||JSON.stringify(j)}let flower={t:turn,kind:'ai-flower',value:120,hash:hash(text),summary:text.slice(0,90).replace(/\s+/g,' ')+'...'};t.flowers.push(flower);t.artifacts.push({turn,hash:flower.hash,text});t.energy+=55;artifact.innerHTML=`<b>AI Flower ${flower.hash}</b><br><pre style="white-space:pre-wrap">${escapeHtml(text)}</pre>`}catch(e){let fallback=`Local symbolic flower\n\nTitle: The Branch That Earned Its Shape\n\nPoem: Roots read noise, leaves spend fire, branches remember what compression could not hide.\n\nInsight: The tree grows fastest when it has enough CPU to test patterns and enough storage to remember them.\n\nError: ${e.message}`;let flower={t:turn,kind:'ai-flower',value:40,hash:hash(fallback),summary:'fallback AI flower; configure local Ollama or API'};t.flowers.push(flower);t.artifacts.push({turn,hash:flower.hash,text:fallback});t.energy+=20;artifact.innerHTML=`<b>Fallback Flower ${flower.hash}</b><br><pre style="white-space:pre-wrap">${escapeHtml(fallback)}</pre>`}}
document.getElementById('ai').onclick=()=>forceFlower(forest[0],'hand-grown-flower',110,'A flower grown by direct attention');
